version: 0.2

phases:
  build:
    commands:
      - aws s3 cp templates/ec2keypair.yaml s3://cfn-nested-sample/security/
      - aws s3 cp templates/iam-policy.yaml s3://cfn-nested-sample/security/
      - aws s3 cp templates/iam-role.yaml s3://cfn-nested-sample/security/
      - aws s3 cp templates/security-group.yaml s3://cfn-nested-sample/security/
