AWSTemplateFormatVersion: "2010-09-09"
Description: Security Group Stack

Parameters:
  VpcId:
    Type: String
    Description: The ID of the VPC
  SecurityGroupName:
    Type: String
    Description: Name of the Security Group

Resources:
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Ref SecurityGroupName
      GroupDescription: Enable HTTP and Session Manager access
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: "0.0.0.0/0"
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: "0.0.0.0/0"
      Tags:
        - Key: Name
          Value: MySG

Outputs:
  SecurityGroupId:
    Description: The ID of the security group
    Value: !Ref EC2SecurityGroup
    Export:
      Name: SecurityGroupId
